### ISSUE TITLE
Add support for TImageCollection

### ISSUE THREAD

**Issue by holgerflick** [skia4delphi/skia4delphi#105]
In order to add images to buttons, toolbars etc. virtual image list support is essential. It would be great being able to use the file formats (without animation, of course) that are available in Skia.

**Comment by viniciusfbb** [comment]
For that we would have to create our own TImageCollection and TVirtualImageList. It's a lot of work because there are designtime editors too. I will accept the feature request but with no expected date to be added.

**Comment by holgerflick** [comment]
I would like to add that I just found out that the GitHub project https://github.com/EtheaDev/SVGIconImageList is based on Skia4Delphi. It also features a different SVG implementation it seems as I have tested several files that are rendered fine with their control but not with Skia4Delphi. So, the image list would only be useful for other file formats which are not really used on Image Lists. I think I will close this issue instead. What are your thoughts?

**Comment by viniciusfbb** [comment]
EtheaDev/SVGIconImageList is a very good library, it implements 4 SVG engines, among them Skia4Delphi (but to use it you must configure it https://github.com/EtheaDev/SVGIconImageList/wiki/Choice-of-Factories) . It is a very used, stable library and will surely solve your problem.

I'll close the topic for now but in the future it would be interesting to add these controls because in skia there are important formats besides svg, such as webp.
