### ISSUE TITLE
Which is the fastest way to show raw bitmap data?

### ISSUE THREAD

**Issue by salvadordf** [skia4delphi/skia4delphi#113]
Hi,

First of all, thank you for your work in Skia4Delphi. I really hope your project is included in Delphi by default. :D 

I added a demo to the CEF4Delphi project called [FMXSkiaBrowser](https://github.com/salvadordf/CEF4Delphi/tree/master/demos/Delphi_FMX_Windows/FMXSkiaBrowser) that uses Skia4Delphi.

I'm still learning a lot about Skia but I would like to know if I'm using the fastest way to show raw bitmap data.

FMXSkiaBrowser uses the off-screen rendering mode and this mode provides an event with a pointer parameter to raw bitmap data. This bitmap data has the web browser contents at that time and it's necessary to copy that data in the event scope.

That demo copies the buffer with [this code](https://github.com/salvadordf/CEF4Delphi/blob/e470e8a5351bffee41943b2fc4b6bc93c1afab43/demos/Delphi_FMX_Windows/FMXSkiaBrowser/uMainForm.pas#L639) : 
`          FImageInfo       := TSkImageInfo.Create(width, height);
          FImage           := TSkImage.MakeRasterCopy(FImageInfo, buffer, FImageInfo.MinRowBytes);`

Then I used a simple TSkPaintBox to draw the TSkImage in the OnDraw event [like this](https://github.com/salvadordf/CEF4Delphi/blob/e470e8a5351bffee41943b2fc4b6bc93c1afab43/demos/Delphi_FMX_Windows/FMXSkiaBrowser/uMainForm.pas#L755) : 
`      ACanvas.ClipRect(ADest);
      ACanvas.DrawImageRect(FImage, TempRect);`

The project file includes [this code](https://github.com/salvadordf/CEF4Delphi/blob/e470e8a5351bffee41943b2fc4b6bc93c1afab43/demos/Delphi_FMX_Windows/FMXSkiaBrowser/FMXSkiaBrowser.dpr#L61) : 
`  GlobalUseMetal := True;
  GlobalUseSkiaRasterWhenAvailable := False;
  GlobalUseSkia := True;`

All this code works fine but I would like to know if there are even faster ways to show the bitmap data with Skia. 

Thanks for your help!

**Comment by viniciusfbb** [comment]
Hello @salvadordf, I'm glad to hear about this new project!

I believe your code is correct.. My only fear is creating a copy every frame. From what I understand CEF renders in a background thread in a buffer and calls TChromiumCore.OnPaint passing the pointer of the pixels of the new frame... In this situation there really isn't much to do. Did you test the result?

Taking the opportunity to pass on 2 tips:
1. Maybe the logic of comparing pixel size x control size, may not work in scale other than 1. Line: https://github.com/salvadordf/CEF4Delphi/blob/e470e8a5351bffee41943b2fc4b6bc93c1afab43/demos/Delphi_FMX_Windows/FMXSkiaBrowser/uMainForm. pas#L717-L718
Maybe it's better to compare bitmap size with something like Round(SceneScale * Control.AbsoluteScale * Control.Width)
2. When using ClipRect, as in SkPaintBox's draw, it must be inside a try finnaly block with ACanvas.Save and ACanvas.Restore, in order to rollback the clipRect you made.

**Comment by salvadordf** [comment]
Hi @viniciusfbb,

Thank you very much for your tips! 

I just added the ACanvas.save and ACanvas.Restore calls to the demo. 

I also removed most of the unnecessary code that was inherited from the other demo that I used as a template for this one. 
The browser resizing is now made in a much simpler way.

This demo uses an external message pump and all the CEF events are triggered in the main application thread. This configuration avoids all thread safety issues.

I tested it with different DPI values and it works fine except for the context menu position. I still need to investigate what's going on with that issue.

Thanks again! :D
