### ISSUE TITLE
Can a static image be played as an animation in TSkAnimatedImage?

### ISSUE THREAD

**Issue by gcanedo** [skia4delphi/skia4delphi#141]
I need it to not use the VCL Timer.

First of all, Thanks

**Comment by viniciusfbb** [comment]
Hi @gcanedo 

No. You should made your animation through Adobe After Effects and then export to lottie file using the BodyMovin plugin.

But, normally, making the animations is a job that doesn't pay, because it's not very easy for those who are not in the area and there are also thousands of ready-made and free animations that you can download from the internet. A good site is [lottiefiles.com](https://lottiefiles.com/featured). Choose your animation and download the Lottie JSON, and upload a TSkAnimatedImage. That simple.

**Comment by gcanedo** [comment]
The image is generated from the program on the fly. And since it is very big, I need to zoom in but it would look more interesting with animation. That's why I require the OnAnimationProgress Event to fire with the single frame image.
![Capture2](https://user-images.githubusercontent.com/12984514/180566103-0f284419-1851-4dbd-91e9-eb5a0ea5b870.PNG)

**Comment by viniciusfbb** [comment]
You need the TSkAnimatedPaintBox control. You will do the ImageDraw manually using the event TSkAnimatedPaintBox.OnAnimationDraw. You don't need to have a timer calling the repaint, just set the duration of your animation and the OnAnimationDraw event will be called in each frame automatically.

**Comment by gcanedo** [comment]
I used it initially, but for some reason when I drag the image when it's big, it slows down the process. And when I switch to TSkAnimatedImage it became very fast. For that reason I wanted to use this component. But thank you very much for your help.

**Comment by viniciusfbb** [comment]
Strange, they both have pretty much the same code and are descendants of TSkCustomAnimatedControl. Anyway, both controls have been rewritten from scratch and improved and will be in our next release in a few weeks.

In addition, in FMX both have the best performance because there is the use of GPU in the control, but in VCL not. We are considering the possibility of implementing the use of hardware acceleration (GPU) in the VCL already in this next release, as per issue #108.

**Comment by gcanedo** [comment]
In fact I think I'm going to move it to FMX with this great engine. Thank you for your great contribution.
