### ISSUE TITLE
How to free a Shader?

### ISSUE THREAD

**Issue by peardox** [skia4delphi/skia4delphi#148]
I'm dynamically creating Shaders at runtime and sometimes I want to throw the current shader away and replace it with a new one.

When throwing the Shader away I want to keep the current image it's using so I make a copy of the bitmap then free the (derived) SkPaintBox and create a new one loading the copied bitmap into that one with a different shader.

Problem is...
![image](https://user-images.githubusercontent.com/1549219/185788303-9518cc95-3239-4d4c-aeeb-9fec39d3e5c7.png)
[TWinAcceleratorKeyRegistry.TAcceleratorKeyReceivers is a StyleBook apparently]

i.e. I'm not cleaning up after myself properly when freeing the Shader (they're x2 cos I tried it twice).

I suspect I need to reverse the effects of one or more of...

```
  Painter.Shader := Effect.MakeShader(True);
  Effect := TSkRuntimeEffect.MakeForShader(ShaderText, AErrorText);
  TexImage := ImageBitmap.ToSkImage;

```

Probably the last one...

[Using Skia4Delphi 3.4.1]

**Comment by viniciusfbb** [comment]
Hi @peardox! This memory leak refers to 2 bitmaps that don't get destroyed in your code. I suspect it's ImageBitmap, because even after the ToSkImage, you should still give it free. On second thought, maybe the ToSkImage could be renamed to MakeSkImage or MakeSnapshot, because it doesn't affect the Bitmap at all, it creates a copy in SkImage format.

**Comment by peardox** [comment]
Re-wrote it using load from for for now
