### ISSUE TITLE
PNG decoding

### ISSUE THREAD

**Issue by FlavienQui** [skia4delphi/skia4delphi#15]
Some PNG files don’t get decoded correctly with Skia4Delphi 2.0.1 on Windows.
Images have been loaded and saved with the following method:

```delphi
procedure DecodeEncodePng(const AFileNameIn, AFileNameOut: string);
var
    LStreamIn, LStreamOut: TStream;
    LImage: ISkImage;
begin
    LStreamOut := nil;
    LStreamIn := TFileStream.Create(AFileNameIn, fmOpenRead or fmShareDenyWrite);
    try
        LStreamOut := TFileStream.Create(AFileNameOut, fmOpenWrite or fmCreate);

        LImage := TSkImage.MakeFromEncoded(LStreamIn);
        LImage.EncodeToStream(LStreamOut, TSkEncodedImageFormat.PNG);
    finally
        LStreamIn.Free;
        LStreamOut.Free;
    end;
end;

DecodeEncodePng('World_time.png', 'World_time_skia.png');
```

World_time.png
![World_time](https://user-images.githubusercontent.com/94360730/141764934-7f6d977c-42de-4e15-bd06-0cb158a1fb82.png)

World_time_skia.png
![World_time_skia](https://user-images.githubusercontent.com/94360730/141764999-17a85298-12b5-44c0-9ae3-c7eebc6a7394.png)

**Comment by viniciusfbb** [comment]
Hi @FlavienQui!

Thank you very much to report this issue.

We had detected this problem a few days ago and we've even fixed it, it was a problem in the decoder implementation and it can affect not only PNG, but other formats as well. However, we will only make the fix available in version 3.0 that is being developed because the solution we propose involves a lot of changes, including binaries for all platforms.

Version 3.0 will be released later this month.

Until then, a workaround would be to use TBitmap to decode and transform into ISkImage. For example:

```delphi
uses
  System.IOUtils,
  Skia,
  Skia.FMX;

procedure DecodeEncodePng(const AInput, AOutput: string);
var
  LInputBitmap: TBitmap;
  LImage: ISkImage;
begin
  LInputBitmap := TBitmap.Create;
  try
    LInputBitmap.LoadFromFile(AInput);
    LImage := LInputBitmap.ToSkImage;
  finally
    LInputBitmap.Free;
  end;
  TFile.WriteAllBytes(AOutput, LImage.EncodeToBytes(TSkEncodedImageFormat.PNG));
end;
```

The same implementation above applies to Vcl as well.

Once again, thanks for the issue report, I will put this World_time.png in the unit tests.

Regards, Vinicius

**Comment by FlavienQui** [comment]
Hi @viniciusfbb,

Thanks a lot for your reply and your great work on this project.

I'm looking forward version 3.0.

Best regards,

Flavien

**Comment by viniciusfbb** [comment]
The problem was solved in new release. Please download new version 3.0.0.
