### ISSUE TITLE
Cannot reinstall a package that links to the current version of Skia because of a procedure entry point error...

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#155]
I have just updated to the latest version of Skia4Delphi on Alexandria with all patches.  However when I recompile a package that has components that use Skia it builds fine, but when I try to install it I get the following message:

![image](https://user-images.githubusercontent.com/18058224/191005902-e2839c99-8ee6-44df-882a-ad2e88ae8568.png)

I've uninstalled and reinstalled the latest build of Skia4Delphi twice, and have fully cleaned and rebuilt my package as well, but I always get the same error.  I'm dead in the water right now, as I can't work without this package installed.  

Help?!

**Comment by viniciusfbb** [comment]
This occurs when there are changes above the implementation that end up generating binary incompatibility. In manual installation this is not a problem because when you uninstall the old skia package, the IDE itself uninstalls the packages that depend on it, which ends up forcing you to recompile all of them after installing skia. When installing via setup/getit this does not occur. When uninstalling the old version, the packages that depend on skia4delphi are still installed and as they are binary incompatible, this error will appear when opening the IDE.

You must uninstall your packages that depend on skia4delphi, install the new version, open the IDE and compile and install them again.

If the error persists, there is still some package that depends on Skia4Delphi that you are not uninstalling. A test would be to uninstall Skia4delphi and open the IDE.

**Comment by TheOriginalBytePlayer** [comment]
While that sounded like it made a lot of sense it didn't work.  Here's what I did:

1. I completely uninstalled Skia
2. I searched my hard drive for any instances of skia.package* and verified they were all gone
3. I relaunched Alexandria.  The only package that refused to load was the same as before
4. I exited Alexandria
5. I installed Skia 3.1.4 via its setup program 
6. I relaunched Alexandria and received exactly the same error.
7. I isolated the Skia derived components to a single package and successfully installed my big package
8. I successfully compiled my new, smaller SkiaDerived package but when I went to install it, I got exactly the same error

![image](https://user-images.githubusercontent.com/18058224/191129983-39e71b93-68fd-4850-af7d-c02efefa355a.png)

9.  Just for kicks I tried to rebuild the Skia Group within Alexandria to see if that made any difference and got an access violation:

![image](https://user-images.githubusercontent.com/18058224/191130491-328cbffb-d017-4cbc-ab55-fc9002960868.png)

Here is the package in question:

[Skia Derived Components.zip](https://github.com/skia4delphi/skia4delphi/files/9602698/Skia.Derived.Components.zip)

**Comment by viniciusfbb** [comment]
![image](https://user-images.githubusercontent.com/11139086/191147764-a013888e-6b75-4e1f-b277-d68754daefd8.png)

After this error, a dialog will appear asking if you want to try loading next time. Press **NO**. (maybe more than 1 error appears, click NO on each one).

![image](https://user-images.githubusercontent.com/11139086/191147787-af9cd7c6-e4db-4869-ab49-afea22a361f5.png)

Then open your package, compile and install. I did just that with your package and it worked here on my 11.2.
PS: I simulated your issue exactly: I first installed an old version of Skia, installed your package then installed the latest version. I opened the IDE and it gave the error, I clicked to **NOT** try to load later, and I opened your package again, compiled and installed it again and everything worked normally.

Check your Library Path, maybe the installer did not correctly remove the directory of the old version of Skia4Delphi.

You can also delete the folders of old versions of skia to ensure that there is no conflict with old binaries...

Manual installation is not as simple as it sounds. I made a [tutorial of manual installation](https://github.com/skia4delphi/skia4delphi/blob/main/Documents/INSTALLATION.md#manual) but I discourage people as it is extremely labor intensive and there will be problems if you don't follow every step exactly.

I want to make it clear that this error is common, it happens with any project that uses setup for installation. The same thing happens to me often because I have 2 packages that use Skia. But after the error, and after reinstalling the pakages that use the Skia, everything has to work exactly as before.

**Comment by viniciusfbb** [comment]
Any news?

**Comment by TheOriginalBytePlayer** [comment]
Sorry, it’s been a frustrating couple of days.

 

The bottom line is yes, I was ultimately able to get it working but I’m not exactly sure what I did that did it.  Unfortunately your basic suggestions of just trying again weren’t sufficient; I had to do a search for every skia package and remove it from my machine, even though I verified all the Delphi paths pointed to the new one and there were no old BPLs anywhere to be found.

 

In any case, thank you so much for your suggestions, your great product, and your follow-through.   

 

It’s extremely rare for even commercial software, and for most open source software it’s like shouting into the void.

 

Cheers,

 

Ken Schafer

**Comment by viniciusfbb** [comment]
Excellent! Unfortunately sometimes it is difficult to our setup detect paths and bpls of old versions of Skia4Delphi especially when trying to install manually. But we are trying to improve the setup experience with each release. To avoid any conflict with older versions I advise always installing in the same directory, and using the default setup directory (`C:\Users\<user>\Documents\Skia4Delphi\`) is a good idea for this.

I will close the issue as I have already solved the problem but feel free to open new ones.
