### ISSUE TITLE
Text width in TFlowLayout varies with GlobalUseSkia on or off

### ISSUE THREAD

**Issue by reggatta** [skia4delphi/skia4delphi#168]
Thank you for publishing this library.  I am using Delphi 11.2 and have a FMX form with a TFlowLayout on it.  In the layout, I have 3 TCheckboxes in a row.  When I use Skia, they overlap each other a little.  When I turn Skia off, they display just fine.  

There is an attached file textNormal.png that shows how it looks without Skia, and a file textOverlapWithSkia.png that shows how it looks with Skia on.  Hopefully you can see how the text overlaps.

I am not recompiling my app, I have a switch in the registry the program reads at startup to determine if GlobalUseSkia should be enabled.

It would be great if there was a fix for this, or let me know if it is something I need to do different in my code.
 
![textOverlapWithSkia](https://user-images.githubusercontent.com/7586289/199812749-2c683787-3384-4a84-b64d-46f8c8f5d066.png)
![textNormal](https://user-images.githubusercontent.com/7586289/199812762-8e265365-f5cf-4010-abe7-53d7634dad2d.png)

**Comment by viniciusfbb** [comment]
Hi, thanks for the reporting the issue.

Are you using the latest version released yesterday? v4.0.0

**Comment by reggatta** [comment]
My apologies, yes, using 4.0!

On Nov 3, 2022, at 12:40 PM, Vinícius Felipe Botelho Barbosa ***@***.***> wrote:

﻿

Hi, thanks for the reporting the issue.

Are you using the latest version released yesterday? v4.0.0

**Comment by viniciusfbb** [comment]
I couldn't reproduce the problem here. I tested it on macOS monterey 12.6.1 in RAD Studio 11.2, without the metal (GlobalUseMetal := False). I also tested by changing the scale, first 1x and then activating the mac's scaled mode (2x scale). The variations on mine were minimal, unlike your print.

It's important to remember that the default macOS renderer doesn't support FontWeight, it just checks if it's regular or bold, while ours renders font weight correctly. Embarcadero has not yet released the property in TFont but you can change it via code: CheckBox1.TextSettings.Font.StyleExt := TFontStyleExt.Create(TFontWeight.Medium);

But I also don't think your case is a problem with FontWeight. Could you give us more information like OS version and testing with metal and without metal? (FMX.Types.GlobalUseMetal := True/False; in your dpr)

**Comment by viniciusfbb** [comment]
@reggatta I investigated a little more now and comparing the text results of the 4 renderers available on macOS, I noticed that there are two groups producing different results:

Group 1
 - **TCanvasQuartz**: Default FMX renderer on macOS
 - **TSkRasterMacOSCanvas**: Skia4Delphi's default renderer on macOS ("GlobalUseSkia := True;")
 - **TMtlCanvas**: Skia4Delphi renderer using Metal on macOS ("GlobalUseSkia := True;" + "GlobalUseMetal := True;")

Group 2
 - **TCanvasGpu**: Default FMX renderer using metal ("GlobalUseMetal := True;")

Based on this, and knowing that the FMX default metal is in the experimental phase, I conclude that the issue is with it and not with the Skia4Delphi render.
