### ISSUE TITLE
Running Demo version is showing "Parameter AContext cannot be nil"

### ISSUE THREAD

**Issue by FernandoWolfepak** [skia4delphi/skia4delphi#169]
![image](https://user-images.githubusercontent.com/102984493/199868317-b9988a96-0be4-4dcf-a962-271da8a76b5e.png)

**Comment by FernandoWolfepak** [comment]
I'm using the lastest version 4.0.0

**Comment by viniciusfbb** [comment]
Hi @FernandoWolfepak, thank you very much to reporting this issue!

I believe I have the fix for this problem, could you test it? Attached is the pinned Skia.FMX.Graphics.pas. You must replace with this new unit in Skia4Delphi\Source\FMX\ folder
After replacing, add this unit to the demo project and then recompile the demo.

[Skia.FMX.Graphics.pas.zip](https://github.com/skia4delphi/skia4delphi/files/9934428/Skia.FMX.Graphics.pas.zip)

**Comment by viniciusfbb** [comment]
Fixed in the [new release v4.0.1](https://github.com/skia4delphi/skia4delphi/releases)
