### ISSUE TITLE
Skia4Delphi text rendering issue in Android (FMX)

### ISSUE THREAD

**Issue by Sniperxx** [skia4delphi/skia4delphi#192]
Hello,
I'm facing weird text rendering issue when using Skia4Delphi + 
Pentire (ksVirtualListView): https://github.com/gmurt/PentireFMX
the problem is illustrated in the next two screenshots:
When Skia4Delphi is disabled the text looks like this:
https://i.ibb.co/6BGWDK1/Skia-Disabled.jpg

When Skia4Delphi is enabled the text looks like this:
https://i.ibb.co/KFv9M8L/Skia-Enabled.jpg

This problem happen in: Samsung Note 10+ (Tested in two different devices)(With Original Samsung Rom)
Android Version:12
One UI Version: 4.1

I've tried viniciusfbb suggested solution but this did not fix the problem under Samsung Note 10+ (my device)
https://stackoverflow.com/questions/74600523/skia4delphi-text-rendering-issue-in-android-fmx

But same test.apk working normally (Even Skia4Delphi is enabled) in other devices such as:
Samsung S10+ (Android 12).
Samsung Note 10 (Android 12).
Samsung J6 (Android 10).
Realme 7 Pro (Android 12).

Test.apk + its source can be downloaded from here: https://www.mediafire.com/file/aj2b6vz02z0pi5v/Test_Project.rar/file

Any help is appreciated
Thanks in advance.

**Comment by marlonnardi** [comment]
To solve it quickly, comment line 3503 of the ksVirtualListView.pas file.

![image](https://user-images.githubusercontent.com/5359931/210134666-4ca879ec-3dba-419e-997d-20967b1fcfe8.png)

Also contact the author of the component, to see if he responds.
https://github.com/gmurt

**Comment by Sniperxx** [comment]
Thanks man its worked.

**Comment by viniciusfbb** [comment]
I confirmed that it really was an issue with the Skia4Delphi render. In some cases, when measuring the text and setting TTextLayout.MaxSize = text size, which is exactly what Pentire's virtual list view does, the text would be trimmed erroneously.

Fixed in last release ([v4.1.0](https://github.com/skia4delphi/skia4delphi/releases))

So now you can go back to the change suggested by @marlonnardi in the Pentire source which will work as expected on both FMX and Skia.
