### ISSUE TITLE
Error on Mac ARM 64-bit 

### ISSUE THREAD

**Issue by PolywickStudio** [skia4delphi/skia4delphi#22]
![priv](https://user-images.githubusercontent.com/8903532/146651281-89f77f55-6d9b-45c5-83d5-b1ebbf230fbc.png)

I get "Privileged Instruction" in Global_Sub_L_Sk4DStream.cpp 

Can you please provide an update for the Mac Arm 64-bit Binary

**Comment by viniciusfbb** [comment]
Hi @PolywickStudio! Thank you very much for reporting the issue.

We need more information. When exactly does this happen? In the execution of some specific code or in the opening of the program?

**Comment by PolywickStudio** [comment]
on opening of the program, when running your demo.

**Comment by viniciusfbb** [comment]
Ok, we'll investigate.

**Comment by viniciusfbb** [comment]
I had access to a Mac ARM for a few minutes, couldn't test it on the current version, but I tested the development version (v3 closed beta) and everything worked fine. So we have 2 possible conclusions:

1) The demo project is in trouble. (There were reports of this in issue #17) In this case, skia will work normally in other projects.

2) Maybe there was a problem that has already been fixed in the development version (which will be available in a few weeks)

Anyway I will leave the issue open until the release of the next version (which as I said has already been tested on Mac ARM).

**Comment by PolywickStudio** [comment]
Do you have an early alpha update. I will be releasing software next week.

**Comment by viniciusfbb** [comment]
@PolywickStudio, I really wanted to make something available to you, but that would be too hasty. The library is not yet mature enough to open an alpha/beta version to the public. Every week the code is drastically changed, redone or even discontinued at some points. Maybe in the next releases we could make a program like that, but not this one.

We are late with version 3.0, but if all goes well, it will be available in 15 days.

About the Mac Arm problem in the current version (2.0.1), as I said, I believe that only the Demo is having a problem, the controls and the api I believe are working correctly.

**Comment by PolywickStudio** [comment]
Any news?
I use only the webp part only. Not the whole Skia rendering API.

**Comment by viniciusfbb** [comment]
@PolywickStudio Yes! A week is what we need 😅

**Comment by viniciusfbb** [comment]
The problem was solved in new release. Please download new version 3.0.0.

**Comment by PolywickStudio** [comment]
Do you have a donate button?

**Comment by viniciusfbb** [comment]
We will add this week. I'll let you know as soon as we add it. :)

**Comment by viniciusfbb** [comment]
@PolywickStudio Thank you so much for wanting to help the project! It's a huge incentive for us to keep striving to improve the library more and more. The Sponsor button has been activated.
