### ISSUE TITLE
True multhreaded Bitmap FMX Canvas

### ISSUE THREAD

**Issue by cosina** [skia4delphi/skia4delphi#223]
EMBT Lock/Unlock upon BeginScene/EndScene block true multithreaded drawing.

I modified SKIA code in the following way:

```
function TSkCanvasBase.DoBeginScene({$IF CompilerVersion < 35}const {$ENDIF}AClipRects: PClipRects;
  AContextHandle: THandle): Boolean;
begin
  Unlock ; //### HERE
  Result := inherited;
  ...
```

and 
```
procedure TSkCanvasBase.DoEndScene;
begin
  Lock ;  //### HERE
  if Parent <> nil then
  ...
```

This fix was tested on Windows only yet and does not pretend to be a full solution. But seems to solve my problem even if calling fake Lock/Unlock is not an elegant nor efficient solution.

**Comment by viniciusfbb** [comment]
Hi @cosina, thanks a lot for the issue!

This lock is something that has bothered us for a long time, as it is important when using GPU bitmaps (like the FMX ones), but in our case, our bitmap is raster (CPU) so it is possible to use it in parallel. Until 11.3 we had some problems removing the lock because System.Messaging was not thread safe and TCanvas and TTextLayout use it. In 11.3 the messaging system became thread safe making our life easier. So in 11.3+ we could adopt this, but there is one last problem: the TFilter (which is the basis of the effects) is not thread safe. All drawings would work normally, minus the image effects/filters. We are looking at a solution for the filters, moreover it seems to be safe to remove the lock in 11.3+.

I will accept the issue because it is something we can and should move forward.

**Comment by viniciusfbb** [comment]
Added as experimental on RAD 12 Beta. Commit 9615e401422a31a3f6cf3dd8532fafe952b58ec0
