### ISSUE TITLE
Drawing RTL Text needs to apply character shaping

### ISSUE THREAD

**Issue by Lasibian** [skia4delphi/skia4delphi#245]
Displaying right-to-left text looks wrong, because character shaping is not applied. Compare the text output of MS Word with that of the demo application.

![image](https://github.com/skia4delphi/skia4delphi/assets/11603066/a1e765b3-ace9-4db7-8fe0-0abf08b1d051)

Tested with version 6.00 Beta 2.

**Comment by randydom** [comment]
Cause you're not using the same font .

**Comment by viniciusfbb** [comment]
@Lasibian Seems that @randydom is right. Are you using the same font family? Do you have more info?

**Comment by Lasibian** [comment]
@randydom got it right. It was because of the different font.

At the moment I still can't use skia with RTL text, because I need the glyph positions of the shaped text. I haven't found a way to get these from the ISkTextBlob.

**Comment by viniciusfbb** [comment]
> At the moment I still can't use skia with RTL text, because I need the glyph positions of the shaped text. I haven't found a way to get these from the ISkTextBlob.

Are you using FMX or VCL? For FMX, I recomend you to use the TSkTextLayout from unit FMX.Skia.Canvas.

**Comment by Lasibian** [comment]
@viniciusfbb I'm using VCL.

**Comment by viniciusfbb** [comment]
@Lasibian The most complete and ideal text manipulation/rendering class (including multiple styles) is the SkParagraph class. There are some examples in our demo and in FMX's own TSkTextLayout (which also uses SkParagraph behind it) to render and manipulate texts, including get the glyph positions.

I will close this issue now because what was reported was not exactly a bug, but feel free to continue the conversation.
