### ISSUE TITLE
Fmx Default gradient does not render

### ISSUE THREAD

**Issue by acztassi** [skia4delphi/skia4delphi#261]
At last version of skia for FMX, it is impossible to render gradient in any control that uses TCanvas.
creating a code like this (OnFormCreate):

  rect.Fill.Color := TAlphaColorRec.Brown;
  rect.Fill.Color := TAlphaColorRec.Brown;
  rect.Fill.Gradient.Color1 := TAlphaColorRec.Brown;
  rect.Fill.Gradient.Color := TAlphaColorRec.Aqua;
  rect.Fill.Kind := TBrushKind.Gradient;
  rect.Fill.Gradient.StartPosition.X := 0.5;
  rect.Fill.Gradient.StartPosition.Y := 1;
  rect.Fill.Gradient.StopPosition.X := 0.5;
  rect.Fill.Gradient.StopPosition.X := 0;

That code results in nothing, until I disable skia, than that works!
I've also tried to use the code below, over the same control, at OnPaint Event!

  rect.Canvas.BeginScene;
  var Painter: ISKPaint;
  Painter := TSkPaint.Create;
  Painter.Style := TSkPaintStyle.Fill;
  Painter.Shader := TSkShader.MakeGradientLinear(TPointF.Create(0.5,1), TPointF.Create(0.5,0), TAlphaColorRec.Brown, TAlphaColorRec.Aqua);
  Painter.AlphaF := 1;
  TSkCanvasCustom(rect.Canvas).canvas.DrawRect(rect.ShapeRect , Painter);
  rect.Canvas.EndScene;

By this way a render occurs, but very different of the native FMX (using the same Gradient positions)

**Comment by acztassi** [comment]
Many thanks for your job!!

**Comment by viniciusfbb** [comment]
> There is another little problem, that I don't know if really is a normal behavior or not
> 
> ```delphi
> // Skia font
> SkFont.MeasureText(' ', AOutRect);
> // AOutRect > results no measure
> ```

It is the Skia behaviour. You can access the Skia fiddle (an online demo of the original Google Skia): 
1. Access the https://fiddle.skia.org/c/@measure_text_bounds
2. Then, change the line `const char text[] = "Skia";` to `const char text[] = " ";`
3. Click on Run
4. You will notice that the black area (OutRect) will not be painted because it is empty. Then, you can change the text to "A" to see that it occurs only with "white text".

**Comment by acztassi** [comment]
Thanks for the explanation!! Have a good Job
