### ISSUE TITLE
Installation failed for Delphi 12

### ISSUE THREAD

**Issue by nickglasier** [skia4delphi/skia4delphi#279]
Error Compiling for RAD Studio 12 (BDS 23.0) - 
Skia.Package.FMX.dproj  - Win32 (code 1).

I tried the install using the default folder first but it also failed, so I tried the user/public/documents/Embarcadero/studio/23.0 folder but it failed there too.

The Build Log.txt files shows the following result at the end of the log.

Build FAILED.

"C:\Users\Public\Documents\Embarcadero\Studio\23.0\Skia4Delphi\Packages\RAD Studio 12 (BDS 23.0)\Skia.Package.FMX.dproj" (default target) (1) ->
(_PasCoreCompile target) -> 
  C:\Users\Public\Documents\Embarcadero\Studio\23.0\Skia4Delphi\Source\FMX\Skia.FMX.Graphics.pas(400): error F2613: Unit 'Skia.FMX.Canvas.Vulkan' not found. [C:\Users\Public\Documents\Embarcadero\Studio\23.0\Skia4Delphi\Packages\RAD Studio 12 (BDS 23.0)\Skia.Package.FMX.dproj]

    0 Warning(s)
    1 Error(s)

Hope this can be resolved soon as I already have a project using skia components with delphi 11, and would like to continue in delphi 12

**Comment by checkdigits** [comment]
The components are already included in Delphi 12 by default - you do not need to install the Skia4Delphi package.  Just open your project and it will work.

You *might* have to tidy up the uses clause if it's an old project but apart from that it will work fine.

![image](https://github.com/skia4delphi/skia4delphi/assets/2126394/b71dd92a-9944-4af9-ac4e-6b512adc800d)

**Comment by TommiPrami** [comment]
How to update Skia4delphi in d12, lets say if you encounter rare bug that us fixed in Skia repo, and Delphi update is ways out?

**Comment by viniciusfbb** [comment]
The RAD Studio 12 have the same version of Skia4Delphi opensource + new units of proprietary features (like skia printer, skia filters, skia vulkan). So, they will sync with this opensource project on each release to add new features / fixes that the opensource could make (like DUnitX and Indy). Anyway, we will update the installer to add support for RAD12+ because right now, the core are the same source, but when we add fixes, the users could use the opensource version before new release of RAD Studio. (It will not affect the extra features added by Embarcadero, it will continue to work).

**Comment by nickglasier** [comment]
Got it. Thanks Ian.  Leave System.Skia but take out the old: Skia, and Skia.FMX , and replace both  with FMX.Skia
