### ISSUE TITLE
How to enable GPU in VCL?

### ISSUE THREAD

**Issue by caryyu** [skia4delphi/skia4delphi#304]
I don't know if this lib supports the VCL hardware acceleration, however, every time when I call `SkPaintBox1.Redraw` with a Timer (200ms interval setup), the painting box is blinking, does anyone here know how I can get the rendering parameters of whether or not is using GPU, and also there's no such `GlobalUseSkia` support in the VCL applications by the way.

**Comment by viniciusfbb** [comment]
@caryyu Skia4Delphi added support for GPU for **VCL** on control TSkAnimatedPaintBox. This was only done in this control because:
1. we have some context limits per application;
2. common drawings, such as those made by TSkLabel, TSkSVG, or even TSkPaintBox, are as performant on the CPU as they are on the GPU. Only more complex drawings, such as shaders and animations, which are ideally made in TSkAnimatedPaintBox, which are better to choose for GPU;
