### ISSUE TITLE
TSkSvg fails to honor opacity on text element

### ISSUE THREAD

**Issue by gwideman** [skia4delphi/skia4delphi#318]
When rendering an SVG file, TSkSvg renders text at full opacity even when it has an opacity attribute set to zero.

Example incorrect render:
![D_SOD-123_F_Fab_test2_SVGEditor](https://github.com/skia4delphi/skia4delphi/assets/1243021/b4969de2-9fd5-4ca3-9824-25c883df3a18)

Should look like:
![D_SOD-123_F_Fab_test2_correct](https://github.com/skia4delphi/skia4delphi/assets/1243021/47c59dac-d97a-411f-8932-ab2440d0e986)

SVG that produces these outputs is attached.

![D_SOD-123_F_Fab_test2](https://github.com/skia4delphi/skia4delphi/assets/1243021/11cf4a76-4be7-4260-9a7d-3625b92510fe)

**Details:**
TSkSvg as supplied with Delphi 12.x updated to Patch 1.
Windows 10 x64  22H2

CAD programs (and possibly others) that produce SVG output apparently sometimes place zero-opacity text into the SVG to make it searchable, when text intended to be rendered is otherwise in stroke form.  Hence the need for an SVG component to either handle text opacity completely, or at least hide the text if opacity is set to zero.

**Comment by viniciusfbb** [comment]
@gwideman I understand your frustration by having on a CAD program a result very different than on TSkSVG. The SVG code of Google Skia is a lightweight implementation, but it is very limited as documented [here](https://github.com/skia4delphi/skia4delphi/blob/main/Documents/SVG.md#limitations).

However, this specific SVG is a bit problematic. I like to use Figma as a reference because it is free and it can load any kind of SVG properly and when it exports as SVG, the Figma tries to export in a common format supported for the most popular SVG libraries on the web, including Skia. I can say that 99% of the SVG exported by Figma can load correctly on Skia.

But my point here is, even Figma is not rendering properly this SVG:
![image](https://github.com/user-attachments/assets/c4e434c7-5e60-4d9d-8d52-334e8a1195e1)

So, in this case I will consider working as expected because of this.
