### ISSUE TITLE
Cursor position in arabic text

### ISSUE THREAD

**Issue by 78Mahdi** [skia4delphi/skia4delphi#326]
Hello

skia work perfect with arabic text, but there is an issue with cursor position, as it is shown in images the caret blink in specified position between "هـ" and "لا" but when i backspace it delete "سـ" instead of "هـ", take in consideration i have set the form bidimode to bdRightToLeft.
![AScreenshot_2024-07-12-12-02-53-86_875cf12ad49906f35c441238cce01c93](https://github.com/user-attachments/assets/cc2cd72e-64e8-4e64-b238-a04b12280afe)
![AScreenshot_2024-07-12-12-03-09-23_875cf12ad49906f35c441238cce01c93](https://github.com/user-attachments/assets/1e6081bc-193d-4530-a1e6-95167859e986)

**Comment by viniciusfbb** [comment]
@78Mahdi Sorry the delay. This is a limitation of FMX text input controls, not on Skia render side. I recommend you open a report for it on [qp.embarcadero.com](https://qp.embarcadero.com). Our recommendation for now when using RightToLeft is to set ControlType=Platform for all TEdit / TMemo (using the native text control), and this is already documented: [skia4delphi/readme#right-to-left](https://github.com/skia4delphi/skia4delphi?tab=readme-ov-file#right-to-left)

Because of this, I'm closing it but feel free to add more details or open another topic.
