### ISSUE TITLE
Initialization Order Chaos -- Show Stopper

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#334]
For some unknown reason every program I compile suddenly is giving me a runtime error on startup and I finally tracked it down to skia.canvas.pas's initialization section which is somehow being called BEFORE the platform initialization so it's failing as there is no default canvas service yet.

I've fully uninstalled skia and reinstalled it but it made no difference.  Also, this happens even if I disable Skia in a firemonkey app and don't use any references to it.

Delphi 12.

Any help you can give me would be brilliant as I am completely dead in the water.

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer I had this problem once when I edited some FMX source and added some Skia unit. Is this the case? Do you have any third-party libraries? As a precaution, it is a good idea to occasionally delete the output folder of the compilation objects, to avoid using old sources.

Most importantly, do you have any projects that simulate this issue?

**Comment by TheOriginalBytePlayer** [comment]
Hmm, yes I do have customized FMX files – which I require and have been using for years, though I’m constantly updating them…

 

I just did a plain vanilla project—nothing but the form--and removed my customized folder from the library search path and it worked fine.    Put it back in, and runtime error 217.

 

So YAY-ish!  At least you’ve given me a path forwards.  I’ve just got to remove all the files from that directory and put them back one-by-one until I find the problem.

 

Thanks so much for your insight though as it at least gives me a path forwards…

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer Another important tip that I said is to delete the output folders of your project. This is important because if you change one FMX unit, compile the project with this new unit, and then delete or remove it from your project, your project may still use it because it will find the dcu on the project output.

Anyway, as it seems to be related to your environment, I will close this issue for now, but feel free to add more information or ask for reopen it if the issue seems on Skia side.
