### ISSUE TITLE
Image does not show sharply as well as fmx original canvas engine

### ISSUE THREAD

**Issue by PonyPC** [skia4delphi/skia4delphi#36]
![ss 2022-02-11](https://user-images.githubusercontent.com/284594/153672060-40db7176-e52d-437a-a2a7-2d07614064ba.png)

Left FMX canvas, Right Skia canvas
Version 3.0 is great, thanks for your contribution. But the image quality is not same as fmx canvas?

**Comment by viniciusfbb** [comment]
Hi @PonyPC!

Try changing the Form.Quality property, try select HighPerformance and HighQuality to see the difference.

**Comment by PonyPC** [comment]
![ss](https://user-images.githubusercontent.com/284594/153674353-a4ddc0c2-1c08-4b1f-a6b9-dcb5ca42c9e0.png)

I have test for 3 different options for quality property. As you can see, the first "o" of skia is not smooth under performance. And both quality and default are blurry.
Platform: Windows

**Comment by PonyPC** [comment]
![ss2](https://user-images.githubusercontent.com/284594/153716545-e905e110-f544-4e0e-8361-d58904939953.png)

Hi, I tested again for diff TSkSamplingOptions with UseCubic, I think maybe we should set True to TSkSamplingOptions.High or TSkSamplingOptions.Medium.

**Comment by viniciusfbb** [comment]
@PonyPC
In Skia4Delphi, there are 3 types of sampling in the following order of quality:

 - Nearest
 - Linear
 - Cubic

So a possible solution would be to use Cubic. The problem is that Skia's Cubic doesn't work the way you might think.

 - First you must fill in parameter B and C, you used 0, I like to use Cubic Catmull-Rom (B: 0; C: 1/2), which is what GIMP uses when you select Cubic method.
 - Skia's Cubic cannot be used directly to downscale an image with a factor greater than 2, the consequence is to deface the image. That's why the results are totally different from Cubic from GIMP or Photoshop. I tried using Cubic 2 months ago, I even opened a bug-report for Google Skia developers: [Poor quality of resize with cubic sampling](https://bugs.chromium.org/p/skia/issues/detail?id=12750). The Google engineer suggests doing multiple resizes with scales of at most 2 until you reach the desired size. The problem is that the performance of this was very bad and as much as the final result has improved, it was not as good as the Cubic from GIMP / Photoshop.
 
Therefore, at first we ruled out using Skia's Cubic.
On the other hand, Linear is a great filter, but it blurs the image a bit.

About these results:

> ![ss](https://user-images.githubusercontent.com/284594/153674353-a4ddc0c2-1c08-4b1f-a6b9-dcb5ca42c9e0.png)

It seems to be working as intended. In HighQuality, despite blurring a little, it's better than FMX. What I could do at first is change using TSkSamplingOptions.High instead of TSkSamplingOptions.Medium, to use BiLinear sampling.

Remembering that no matter how good the sampling filter is, we will never have a result as good as an SVG. I highly advise replacing all these types of images with SVG.

**Comment by PonyPC** [comment]
Thanks for the advice. Downscale the scenery image over 2 factors may not be noticeable, but the text or detail will be intermittently. See the "English" below, some parts are thin than 1 pixel, and not clearly for reading.

> ![](https://user-images.githubusercontent.com/16469061/153615217-53e851a3-c20d-4cb9-92fb-b9b18319c342.png#gh-dark-mode-only)

In photoshop we can render the text by sharply or smoothing for clearly. Although downscaling over 2 factors is not perfect like OpenGL, but still good for reading and noticing photo details. I'm doing video playing on TImage so it's impossible to use SVG.

**Comment by viniciusfbb** [comment]
This is a previously reported issue in Skia/Xamarin/Chrome. There are several topics about this, for example: https://bugs.chromium.org/p/chromium/issues/detail?id=562162 

So far it is not considered a bug, it is the expected operation of the Linear algorithm. As you yourself suggested, the best choice is to switch to Cubic. We did performance tests and there was no impact. However, we will refuse your pull request as the values of parameters B and C are not ideal. Instead, we opted for Mitchell (B = 1/3, C = 1/3), which is Skia's default Cubic. Learn more about Cubic: https://entropymine.com/imageworsener/bicubic/
