### ISSUE TITLE
Know issues section missing from README.md

### ISSUE THREAD

**Issue by birbilis** [skia4delphi/skia4delphi#389]
at README.md contents there is a missing section, Known issues
https://github.com/skia4delphi/skia4delphi/blob/6122214fcfaa743e51e7b1ad63a578e0e81b8047/README.md?plain=1#L78

where can I learn more about the issue title mentioned there?

> - [Known issues](#known-issues)
>>  - [Universal macOS Binary](#universal-macos-binary)
>>  - [Submit your app to the Mac App Store](#submit-your-app-to-the-mac-app-store)

**Comment by viniciusfbb** [comment]
@birbilis Thanks for the report. In fact, the readme shouldn't have "Known issues" section as those known issues was fixed on last release after the adoption of static library on macOS.

**Comment by birbilis** [comment]
Thanks for clarifying that. Is there option of using static library on the other platforms? (esp. on Windows for when shipping one's app as a single executable wihout installer)

**Comment by viniciusfbb** [comment]
@birbilis It is not optional. Windows and Linux are dynamic and macOS, iOS, iOSSimulator and Android are static in the latest version (present in RAD Studio 12.2). There are also a couple of requests for Windows static: #330 #317 #130.

Static linking of C++ libraries in Delphi Windows has historically been impossible due to limitations mainly in the Delphi linker, such as maximum symbol size, unsupported mangled names, symbol conflicts, etc. However, some time ago we did some testing and managed to develop some tools to adapt the C++ library objects to avoid the linker limitations and we even developed a small demo running part of Skia completely statically in Delphi, without DLLs.

However, developing a static version of Skia4Delphi on Windows, although proven to be possible, would take months of dedication. And this would only be a workaround for the real problem, present in the Delphi linker. Furthermore, it is likely that this would bring more complexity to updating Google Skia from Skia4Delphi (and we have not done this for 2 years).

**Comment by birbilis** [comment]
I'd expect to be able to use the new C++ engine of C++ Builder to make a wrapping package that would then use from Delphi. Similar to how in the .NET world they would use MS VC++ extensions to wrap C++ libs and access them from other .NET languages.

**Comment by viniciusfbb** [comment]
@birbilis The new Win64 modern toolchain of C++Builder will not help for this. You can consume Delphi packages, on C++Builder but you cannot consume C++ on Delphi side. I explained just few limitations, but there are much more limitations like the crt/libc++ initialization and finalization, C++ exception handle, unsupported symbols name produced by lambdas and much more...

It is possible and we proved it, but it is a lot of work, and it is not a priority for now.
