### ISSUE TITLE
Missing Linux support (Delphi 11 Alexandria - Enterprise) 

### ISSUE THREAD

**Issue by SiveaITA** [skia4delphi/skia4delphi#44]
Skia4Delphi Ver. 3.0.0.0

There is no define about TGrCanvasGL (or something like TSkCanvasRasterLinux) in line 1263 of Skia.FMX.Graphics when define Linux64 as target OS: 

"  {$IF defined(MSWINDOWS)}
  if GlobalUseSkiaRasterWhenAvailable then
    Result := TSkCanvasRasterWindows
  else
    Result := TGrCanvasGL;
  {$ELSEIF DEFINED(MACOS)}
  if GlobalUseMetal then
    Exit(TGrCanvasMetal)
  else
    {$IFDEF IOS}
    Result := TGrCanvasGL;
    {$ELSE}
    Result := TSkCanvasRasterMacOS;
    {$ENDIF}
  {$ELSE}
  Result := TGrCanvasGL;    <----------------------- THIS if LINUX64 DEFINED
  {$ENDIF}
" 
TGrCanvasGL is defined in Skia.FMX.Canvas.GL, but for Linux nothing is declared.

Demo is not compiled for Linux64 (FMXLinux is installed), I miss something ?

**Comment by viniciusfbb** [comment]
Thank you so much for reporting! The problem has been fixed in new release v3.0.1. But it is worth mentioning that the binary was pre-built for systems based on Debian, such as Ubuntu. If you need it for another distro it will be necessary to recompile the Skia binary. For more informations: https://github.com/skia4delphi/skia4delphi/blob/main/Documents/BUILD.md
