### ISSUE TITLE
Compile for Android 4.X

### ISSUE THREAD

**Issue by diegoverdan** [skia4delphi/skia4delphi#97]
According to the Skia documentation (https://stringfixer.com/en/Skia_Graphics_Engine) it can be used from Android 4.1 (JellyBean) or later. When trying to compile for Android 4.4 with Rad Studio 10.2.3 (Tokyo) I get the following message: The Skia does not support the Android platform in this RAD Studio version.
Can't use Skia4Delphi on older versions of Android?

**Comment by viniciusfbb** [comment]
Hi @diegoverdan!

The versions supported on each platform by Skia are out of date on their website. Skia and Skia4Delphi currently support Android 5.0+. However, the error message that appeared to you was not because of the Android version, it was because of your RAD Studio version. Currently, we officially support Android from RAD Studio Rio+. See more information here: https://github.com/skia4delphi/skia4delphi#compatibility

**Comment by viniciusfbb** [comment]
I will close this topic as it is not an issue, but feel free to continue the conversation or open new issues.
